index:
    path: /
    controller: App\Controller\ArticleController::homepage

news:
    path: /news/{id}
    controller: App\Controller\ArticleController::news

ajax_url:
    path: /ajax_url
    controller: App\Controller\ArticleController::ajaxUrl

markdown:
    path: /markdown
    controller: App\Controller\ArticleController::mark